In [1]:
!pip install -U --pre mxnet-cu101mkl  # updating mxnet to at least v1.6

Requirement already up-to-date: mxnet-cu101mkl in /usr/local/lib/python3.6/dist-packages (1.6.0b20191006)


In [0]:
from mxnet import np, npx
npx.set_np()

In [0]:
x = np.arange(10) # 0-9

In [4]:
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
x.shape

(10,)

In [6]:
x.reshape((5, 2))

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [7]:
x.reshape((2, 5))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [8]:
np.empty((2, 3))

array([[2.9973843e-36, 0.0000000e+00, 4.4841551e-44],
       [0.0000000e+00,           nan, 0.0000000e+00]])

In [9]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.random.normal(size = (2, 3))

array([[2.2122064 , 1.1630787 , 0.7740038 ],
       [0.4838046 , 1.0434403 , 0.29956347]])

In [11]:
x = np.arange(10) + 1
y = np.arange(10)
x + y, x - y, x * y, x / y

(array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([ 0.,  2.,  6., 12., 20., 30., 42., 56., 72., 90.]),
 array([      inf, 2.       , 1.5      , 1.3333334, 1.25     , 1.2      ,
        1.1666666, 1.1428572, 1.125    , 1.1111112]))

In [12]:
np.exp(x)

array([2.7182817e+00, 7.3890562e+00, 2.0085537e+01, 5.4598148e+01,
       1.4841316e+02, 4.0342880e+02, 1.0966332e+03, 2.9809580e+03,
       8.1030840e+03, 2.2026465e+04])

In [13]:
x = np.random.uniform(low = 0, high = 100, size = (2, 3))
y = np.random.normal(size = (4, 3))
print(x.shape, y.shape)
np.concatenate([x, y], axis = 0)

(2, 3) (4, 3)


array([[54.48832   , 84.725174  , 42.36548   ],
       [62.35637   , 64.58941   , 38.43817   ],
       [-1.771029  , -0.5459446 , -0.45138445],
       [-2.3556297 ,  0.57938355,  0.5414402 ],
       [-1.856082  ,  2.6785066 , -1.9768796 ],
       [ 1.2546344 , -0.20801921, -0.54877394]])

In [14]:
x.sum()

array(346.96292)

In [15]:
x.sum(axis = 0), x.sum(axis = 1)

(array([116.84469, 149.31458,  80.80365]), array([181.57898, 165.38394]))

In [16]:
x[1:3, :]

array([[62.35637, 64.58941, 38.43817]])

In [17]:
x = np.random.normal(size = (2, 3))
y = np.random.normal(size = (2, 3))
before = id(y)
y = y + x
id(y) == before # Moved to new memory location

False

In [18]:
z = np.zeros_like(x)
before = id(z)
z[:] = y + x
id(z) == before # Overwrite

True