In [1]:
!pip install mxnet

from mxnet import np, npx
npx.set_np()

x = np.array([1.0])
y = np.array([2.0])

x + y, x * y, x / y, x ** y

(array([3.]), array([2.]), array([0.5]), array([1.]))

In [2]:
x = np.array([i for i in range(10)])
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
len(x), x.shape

(10, (10,))

In [4]:
mat = np.arange(30).reshape((5, 6))
mat

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]])

In [5]:
mat.T

array([[ 0.,  6., 12., 18., 24.],
       [ 1.,  7., 13., 19., 25.],
       [ 2.,  8., 14., 20., 26.],
       [ 3.,  9., 15., 21., 27.],
       [ 4., 10., 16., 22., 28.],
       [ 5., 11., 17., 23., 29.]])

In [6]:
tens = np.arange(40).reshape((2, 4, 5))
tens

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.]]])

In [7]:
B = tens.copy()
tens + B == 2 * tens

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [8]:
B * tens # Does element-wise multiplication

array([[[0.000e+00, 1.000e+00, 4.000e+00, 9.000e+00, 1.600e+01],
        [2.500e+01, 3.600e+01, 4.900e+01, 6.400e+01, 8.100e+01],
        [1.000e+02, 1.210e+02, 1.440e+02, 1.690e+02, 1.960e+02],
        [2.250e+02, 2.560e+02, 2.890e+02, 3.240e+02, 3.610e+02]],

       [[4.000e+02, 4.410e+02, 4.840e+02, 5.290e+02, 5.760e+02],
        [6.250e+02, 6.760e+02, 7.290e+02, 7.840e+02, 8.410e+02],
        [9.000e+02, 9.610e+02, 1.024e+03, 1.089e+03, 1.156e+03],
        [1.225e+03, 1.296e+03, 1.369e+03, 1.444e+03, 1.521e+03]]])

In [10]:
np.multiply(B, tens) # Does the same thing as above

array([[[0.000e+00, 1.000e+00, 4.000e+00, 9.000e+00, 1.600e+01],
        [2.500e+01, 3.600e+01, 4.900e+01, 6.400e+01, 8.100e+01],
        [1.000e+02, 1.210e+02, 1.440e+02, 1.690e+02, 1.960e+02],
        [2.250e+02, 2.560e+02, 2.890e+02, 3.240e+02, 3.610e+02]],

       [[4.000e+02, 4.410e+02, 4.840e+02, 5.290e+02, 5.760e+02],
        [6.250e+02, 6.760e+02, 7.290e+02, 7.840e+02, 8.410e+02],
        [9.000e+02, 9.610e+02, 1.024e+03, 1.089e+03, 1.156e+03],
        [1.225e+03, 1.296e+03, 1.369e+03, 1.444e+03, 1.521e+03]]])

In [11]:
tens1 = np.arange(6).reshape((2, 3))
tens1.sum(axis = 0) # Reduction sum

array([3., 5., 7.])

In [12]:
tens1.sum(axis = 0, keepdims = True) # Non-reduction column sum

array([[3., 5., 7.]])

In [13]:
tens1.sum(axis = 1, keepdims = True) # Non-reduction row sum

array([[ 3.],
       [12.]])

In [14]:
cs = tens1.sum(axis = 0, keepdims = True) # Non-reduction column sum
rs = tens1.sum(axis = 1, keepdims = True) # Non-reduction row sum
tens1 / cs, tens1 / rs

(array([[0.        , 0.2       , 0.2857143 ],
        [1.        , 0.8       , 0.71428573]]),
 array([[0.        , 0.33333334, 0.6666667 ],
        [0.25      , 0.33333334, 0.41666666]]))

In [16]:
tens1.cumsum(axis = 0) # Top to bottom in column

array([[0., 1., 2.],
       [3., 5., 7.]])

In [17]:
tens1.cumsum(axis = 1) # Left to right in row

array([[ 0.,  1.,  3.],
       [ 3.,  7., 12.]])

In [19]:
np.dot(tens1, tens1.T) # Does matrix multiplication. Doesn't have matmul!

array([[ 5., 14.],
       [14., 50.]])

In [20]:
v = np.array([3, -4])
np.linalg.norm(v) # Vector (L2) norm

array(5.)

In [21]:
np.abs(v).sum() # Vector (L1) norm

array(7.)

In [22]:
np.linalg.norm(np.ones((4, 9))) # Frobenius norm of matrix: sum of squares of each element

array(6.)